image: "python:3"

services:
    - mysql


before_script:
    python3 setup.py easy_install

stages:
    - test
    - upload

job1:
    stage: test
    script:
        - python3 setup.py test
    variables:
        MYSQL_DATABASE: auth_test


