

services:
    - mysql

variables:
    MYSQL_DATABASE: "auth_test"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    PAMMYSQL_TEST_MYSQL_HOST: "mysql"

stages:
    - test
    - upload

test_python3:
    image: "python:3"
    stage: test
    script:
        - python setup.py test

test_python2:
    image: "python:2"
    stage: test
    script:
        - python setup.py test

upload:
    stage: upload
    script:
        - pip install twine wheel babel
        - python3 setup.py compile_catalog -d pammysqltools/locales
        - python3 setup.py sdist bdist_wheel
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags
