image: "python:3"

services:
    - mysql


variables:
    MYSQL_DATABASE: "auth_test"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

stages:
    - test
    - upload

job1:
    stage: test
    script:
        - python3 setup.py test

job2:
    stage: upload
    script:
        - pip install twine
        - python3 setup.py sdist bdist bdist_egg
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags
