image: "python:3"

services:
    - mysql


variables:
    MYSQL_DATABASE: "auth_test"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

before_script:
    - python3 setup.py build

stages:
    - test
    - upload

job1:
    stage: test
    script:
        - python3 setup.py test


